#!/usr/bin/env bash
# Script: 7-highlander
# Displays "To infinity and beyond" indefinitely
# Prints "I am invincible!!!" when receiving SIGTERM

trap 'echo "I am invincible!!!"' SIGTERM

while true
do
  echo "To infinity and beyond"
  sleep 2
done

